/*
 * generated by Xtext
 */
package de.fhws.rdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.builder.IXtextBuilderParticipant;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RDSLUiModule extends de.fhws.rdsl.ui.AbstractRDSLUiModule {
    public RDSLUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }

    @Override
    public Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
        return MultipleResourceBuilderParticipant.class;
    }
}
