/*
 * generated by Xtext
 */
package com.xtext.rest.rdsl;
 
import com.xtext.rest.rdsl.generator.MultipleResourceRestDslGenerator;

/**
 * Use this class to register components to be used public void doGenerate(ResourceSet input, IFileSystemAccess fsa);at runtime / without the Equinox extension registry.
 */
public class RestDslRuntimeModule extends com.xtext.rest.rdsl.AbstractRestDslRuntimeModule {
	/**
	 * Bind the custom Generator to the runtime
	 * @return Resource generator which can handle multiple input files
	 */
	public Class<? extends IMultipleResourceGenerator> bindIMultipleResourceGenerator() {
		return MultipleResourceRestDslGenerator.class;
	}

}
