/*
 * generated by Xtext
 */
package com.xtext.rest.rdsl;
 
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

import com.google.inject.Binder;
import com.google.inject.Singleton;
import com.rest.rdsl.unittests.UnitTestOutputConfigurationProvider;
import com.xtext.rest.rdsl.generator.MultipleResourceRestDslGenerator;

/**
 * Use this class to register components to be used public void doGenerate(ResourceSet input, IFileSystemAccess fsa);at runtime / without the Equinox extension registry.
 */
public class RestDslRuntimeModule extends com.xtext.rest.rdsl.AbstractRestDslRuntimeModule {
	/**
	 * Bind the custom Generator to the runtime
	 * @return Resource generator which can handle multiple input files
	 */
	public Class<? extends IMultipleResourceGenerator> bindIMultipleResourceGenerator() {
		return MultipleResourceRestDslGenerator.class;
	}

	@Override
	public void configure(Binder binder)
	{
		super.configure(binder);
		binder.bind(IOutputConfigurationProvider.class)
			  .to(UnitTestOutputConfigurationProvider.class)
			  .in(Singleton.class);
	}
}
