/*
 * generated by Xtext
 */
package com.xtext.rest.rdsl;
 
import com.xtext.rest.rdsl.generator.IMultipleResourceGenerator;
import com.xtext.rest.rdsl.generator.RestDslGenerator;

/**
 * Use this class to register components to be used public void doGenerate(ResourceSet input, IFileSystemAccess fsa);at runtime / without the Equinox extension registry.
 */
public class RestDslRuntimeModule extends com.xtext.rest.rdsl.AbstractRestDslRuntimeModule {
	/**
	 * Bind the custom Generator to the runtime
	 * @return Resource generator which can handle multiple input files
	 */
	public Class<? extends IMultipleResourceGenerator> bindIMultipleResourceGenerator() {
	    Class<?> clazz;
        try {
            clazz = Class.forName("com.xtext.rest.rdsl.generator.MultipleResourceRestDslGenerator");
            if(clazz != null) {
                return (Class<? extends IMultipleResourceGenerator>) clazz;
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return null;
	}

}
