/*
 * generated by Xtext
 */
package com.xtext.rest.rdsl.ui.contentassist

import com.xtext.rest.rdsl.ui.contentassist.AbstractRestDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RestDslProposalProvider extends AbstractRestDslProposalProvider {
}
