/*
 * generated by Xtext
 */
package com.xtext.rest.rdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.builder.IXtextBuilderParticipant;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RestDslUiModule extends com.xtext.rest.rdsl.ui.AbstractRestDslUiModule {
	public RestDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		return MultipleResourceBuilderParticipant.class;
	}
	
}
