/*
 * generated by Xtext
 */
package de.fhws.rdsl.ui.contentassist

import de.fhws.rdsl.ui.contentassist.AbstractRDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RDSLProposalProvider extends AbstractRDSLProposalProvider {
}
