<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="table" nsURI="http://www.fhws.de/rdsl/model/table" nsPrefix="table">
  <eClassifiers xsi:type="ecore:EClass" name="TableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//TableElement #//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//TableMember" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiers" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableMember" eSuperTypes="#//TableElement #//Named"/>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableAttribute" eSuperTypes="#//TableMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flags" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableReference" eSuperTypes="#//TableMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceTable" eType="#//ReferenceTable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="list" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableContainment" eSuperTypes="#//TableMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="list" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTable" eType="#//SubTable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubTable" eSuperTypes="#//Table"/>
  <eClassifiers xsi:type="ecore:EClass" name="RootTable" eSuperTypes="#//Table"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceTable" eSuperTypes="#//Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//TableReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//TableReference"/>
  </eClassifiers>
</ecore:EPackage>
