/*
* generated by Xtext
*/
package de.fhws.rdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RDSLStandaloneSetup extends RDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new RDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

