/*
 * generated by Xtext
 */
package de.fhws.rdsl;

import java.util.List;

import com.google.common.collect.Lists;

import de.fhws.rdsl.generator.IMultipleResourceGenerator;

public class RDSLRuntimeModule extends de.fhws.rdsl.AbstractRDSLRuntimeModule {

	public IMultipleResourceGenerator bindIMultipleResourceGenerator() {
		try {
			List<IMultipleResourceGenerator> generators = Lists.newArrayList();
			Class<?> dbGeneratorClazz = Class.forName("de.fhws.rdsl.generator.db.DBMultipleResourceGenerator");
			generators.add((IMultipleResourceGenerator) dbGeneratorClazz.newInstance());
			// Class<?> restGeneratorClazz =
			// Class.forName("de.fhws.rdsl.generator.rest.RESTMultipleResourceGenerator");
			// generators.add((IMultipleResourceGenerator)
			// restGeneratorClazz.newInstance());
			return new CompositeMultipleResourceGenerator(generators);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

}
