/*
 * generated by Xtext
 */
package de.fhws.rdsl;

import de.fhws.rdsl.generator.IMultipleResourceGenerator;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class RDSLRuntimeModule extends de.fhws.rdsl.AbstractRDSLRuntimeModule {
	/**
	 * Bind the custom Generator to the runtime
	 *
	 * @return Resource generator which can handle multiple input files
	 */
	public Class<? extends IMultipleResourceGenerator> bindIMultipleResourceGenerator() {
		Class<?> clazz;
		try {
			clazz = Class.forName("de.fhws.rdsl.generator.db.DBMultipleResourceGenerator");
			if (clazz != null) {
				return (Class<? extends IMultipleResourceGenerator>) clazz;
			}
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		return null;
	}

}
