package com.xtext.rest.rdsl.generator.internals;

import com.xtext.rest.rdsl.management.Constants;
import com.xtext.rest.rdsl.management.Naming;
import com.xtext.rest.rdsl.management.PackageManager;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;

/**
 * Class for JSON Collection generation
 */
@SuppressWarnings("all")
public class JSONCollectionGenerator {
  private IFileSystemAccess fsa;
  
  public JSONCollectionGenerator(final IFileSystemAccess fsa) {
    this.fsa = fsa;
  }
  
  /**
   * Generates a class for similar to the structure of application/vnc.collection+json MediaType.
   */
  public void generate() {
    String _generationLocation = Naming.CLASS_JSONCOLLECTION.getGenerationLocation();
    String _plus = (_generationLocation + Constants.JAVA);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _resourcePackage = PackageManager.getResourcePackage();
    _builder.append(_resourcePackage, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import java.util.ArrayList;");
    _builder.newLine();
    _builder.append("import java.net.URI;");
    _builder.newLine();
    _builder.append("import ");
    String _classImport = Naming.CLASS_LINK.getClassImport();
    _builder.append(_classImport, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _classImport_1 = Naming.CLASS_OBJPARENT.getClassImport();
    _builder.append(_classImport_1, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(Naming.CLASS_JSONCOLLECTION, "");
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private List<");
    _builder.append(Naming.CLASS_OBJPARENT, "\t");
    _builder.append("> items = new ArrayList<");
    _builder.append(Naming.CLASS_OBJPARENT, "\t");
    _builder.append(">();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private List<");
    _builder.append(Naming.CLASS_LINK, "\t");
    _builder.append("> links = new ArrayList<");
    _builder.append(Naming.CLASS_LINK, "\t");
    _builder.append(">();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private String version = \"0.1\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String href;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private List<");
    _builder.append(Naming.CLASS_JSONCOL_QUERY, "\t");
    _builder.append("> query = new ArrayList<");
    _builder.append(Naming.CLASS_JSONCOL_QUERY, "\t");
    _builder.append(">();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(Naming.CLASS_JSONCOLLECTION, "\t");
    _builder.append("(String href){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.href = href;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(Naming.CLASS_JSONCOLLECTION, "\t");
    _builder.append("(URI uri){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.href = uri.toString();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(Naming.CLASS_JSONCOLLECTION, "\t");
    _builder.append("(String href, List<");
    _builder.append(Naming.CLASS_OBJPARENT, "\t");
    _builder.append("> items){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this(href);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.items = items;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<");
    _builder.append(Naming.CLASS_OBJPARENT, "\t");
    _builder.append("> getItems(){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("if(this.items != null){");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return this.items;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return new ArrayList<");
    _builder.append(Naming.CLASS_OBJPARENT, "\t\t");
    _builder.append(">();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setItems(List<");
    _builder.append(Naming.CLASS_OBJPARENT, "\t");
    _builder.append("> items){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("if(items != null){");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("this.items = items;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getHref() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return href;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setHref(String href) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.href = href;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getVersion() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return version;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setVersion(String version) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.version = version;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<SimpleLink> getLinks() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return links;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setLinks(List<SimpleLink> links) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.links = links;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<");
    _builder.append(Naming.CLASS_JSONCOL_QUERY, "\t");
    _builder.append("> getQuery() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return query;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void addQuery(");
    _builder.append(Naming.CLASS_JSONCOL_QUERY, "\t");
    _builder.append(" query) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.query.add(query);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    this.fsa.generateFile(_plus, _builder);
  }
  
  /**
   * Generates a class for query support inside the JSON Collection media type
   */
  public void geneateQueryClass() {
    String _mainPackage = Constants.getMainPackage();
    String _plus = (_mainPackage + Constants.RESOURCEPACKAGE);
    String _plus_1 = (_plus + "/");
    String _plus_2 = (_plus_1 + Naming.CLASS_JSONCOL_QUERY);
    String _plus_3 = (_plus_2 + Constants.JAVA);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _resourcePackage = PackageManager.getResourcePackage();
    _builder.append(_resourcePackage, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(Naming.CLASS_JSONCOL_QUERY, "");
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String href;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String rel;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String prompt;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String value;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(Naming.CLASS_JSONCOL_QUERY, "\t");
    _builder.append("(){}");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getHref() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return href;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setHref(String href) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.href = href;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getRel() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return rel;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setRel(String rel) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.rel = rel;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getPrompt() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return prompt;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setPrompt(String prompt) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.prompt = prompt;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getName() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setName(String name) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.name = name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getValue() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return value;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setValue(String value) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.value = value;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    this.fsa.generateFile(_plus_3, _builder);
  }
}
